#! /bin/bash
usage_error () {
  cat << EOF
------------------------------------------------------------------
Name: bd
Version: 1.02

------------------------------------------------------------------
Description: Go back to a specified directory up in the hierarchy.

------------------------------------------------------------------
How to use:

Please refer https://github.com/vigneshwaranr/bd

EOF
}

newpwd() {
  oldpwd=$1
  case "$2" in
	# Case sensitive
    -s)
      pattern=$3
	  if [ "$pattern" == "$HOME" -o "$pattern" == "~" ]
	  then
	  	NEWPWD=$HOME
      elif [ "$pattern" == "/" ]
	  then
	    NEWPWD='/'
	  else
		NEWPWD=$(echo $oldpwd | sed 's|\(.*/'$pattern'[^/]*/\).*|\1|')
	  fi
      ;;
	# Case insensitive
    -si)
      pattern=$3
	  if [ "$pattern" == "$HOME" -o "$pattern" == "~" ]
	  then
	  	NEWPWD=$HOME
      elif [ "$pattern" == "/" ]
	  then
	    NEWPWD='/'
	  else
        NEWPWD=$(echo $oldpwd | perl -pe 's|(.*/'$pattern'[^/]*/).*|$1|i')
	  fi
      ;;
    *)
      pattern=$2
      NEWPWD=$(echo $oldpwd | sed 's|\(.*/'$pattern'/\).*|\1|')
  esac
}

if [ $# -eq 0 ]
then
  usage_error
else
  oldpwd=$(pwd)

  newpwd "$oldpwd" "$@"
  
  if [ "$NEWPWD" = "$oldpwd" ]
  then
	echo "NEWPWD: $NEWPWD"
    echo "No such occurrence."
  else
    echo $NEWPWD
    cd "$NEWPWD"
  fi
  unset NEWPWD
fi
